### ISSUE TITLE
FUT20 Integration

### ISSUE THREAD

**Issue by oRastor** [oRastor/fut20-web-app#1]
I already received a few emails with issues about working this script for FUT20.

Today I launched the web app for the first time. After all the starting steps, I saw that transfers were not available to me. I don’t know if I will even buy FIFA 20. Not to mention whether I will play 30 matches now, which are necessary for opening transfers.

To set up the script, I need a working account with available transfers for one day or several hours.

**Comment by DonZlp** [comment]
Sent you an email

**Comment by oRastor** [comment]
UI fixed

**Comment by MvB47** [comment]
It still doesn't work for me. I have autobuyer menu, but it stays idle when i search

**Comment by LaKo13** [comment]
Same problem here, set-up seems to be working but does not do anything when you create a autobuy function.

**Comment by VatsaPatel** [comment]
Don't worry,  got fully working on mine and added some new features as well. will put a PR in a day or so.

**Comment by LaKo13** [comment]
Awesome - cheers! :)

**Comment by MvB47** [comment]
That would be great!!

**Comment by PieterCc** [comment]
@VatsaPatel do you have an autobuyer?

**Comment by BzRk88** [comment]
Oh that would be awesome🎉🎉🎉🎉

**Comment by Verdagen** [comment]
We are all waiting for the update. Thanks for working on autobuyer. :)

**Comment by VatsaPatel** [comment]
He guys, I am thinking of adding features:
 - multiple player buy list, that will repeatedly analyze the market to find a snipe and instantly sell it for profit at that moment.
- Bidding watcher: auto bid players in last 30 sec at cheap from the wishlist, whilst watching current market price.
- Multiple filter support: run script on multiple filters and rotate through them instead of sticking to 1 card for 2 hours.
- Squad Overview: assess if unused card's price has skyrocketed due to SBC.

So what are your views? Any additions you would like?.  Also, at the moment I am running into limitations of tampermonkey being sandboxed, So would you be fine with an electron app? Also market scraping would need to be done by a server, so don't know how to distribute access to everybody.

**Comment by oRastor** [comment]
@VatsaPatel hi, good idea. Can you at first make PR with working autobuyer search?)

I received 20+ emails from 20 September with requesting of autobuyer fix for FUT20. And everyone wants at least simple autobuyer realization for the time of game start.

Thanx for understanding!

**Comment by BzRk88** [comment]
Sounds al good. But just what orest is saying if you for now can put up a simpel working version of the autobuyer that would be great. Just like the one in 19. The rest of the additions would be great for an update. They are very cool.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Orest Budzhak <notifications@github.com>
Verzonden: Monday, September 23, 2019 12:08:46 PM
Aan: oRastor/fut20-web-app <fut20-web-app@noreply.github.com>
CC: BzRk88 <hendriks_jimmy@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [oRastor/fut20-web-app] FUT20 Integration (#1)


@VatsaPatel<https://github.com/VatsaPatel> hi, good idea. Can you at first make PR with working autobuyer search?)

I received 20+ emails from 20 September with requesting of autobuyer fix for FUT20. And everyone wants at least simple autobuyer realization for the time of game start.

Thanx for understanding!

**Comment by Verdagen** [comment]
The basic version of autobuyer was great for me. New features would be good, but for now it's enough to update the old version. The rest of the functions can be added over time.

**Comment by BzRk88** [comment]
Same here. The basic autobuyer was good enough

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Verdagen <notifications@github.com>
Verzonden: Monday, September 23, 2019 1:21:19 PM
Aan: oRastor/fut20-web-app <fut20-web-app@noreply.github.com>
CC: BzRk88 <hendriks_jimmy@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [oRastor/fut20-web-app] FUT20 Integration (#1)


The basic version of autobuyer was great for me. New features would be good, but for now it's enough to update the old version. The rest of the functions can be added over time.

**Comment by LaKo13** [comment]
I agree! Basic autobuyer would be nice to leverage now before the actual game starts. Thanks a lot for updating.

**Comment by BzRk88** [comment]
So i think i can speak for all of us. We cant wait till you can get the link online. Just a basic version is good for now. A running version. Would help us a lot

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Laurent Koerge <notifications@github.com>
Verzonden: Monday, September 23, 2019 2:27:34 PM
Aan: oRastor/fut20-web-app <fut20-web-app@noreply.github.com>
CC: BzRk88 <hendriks_jimmy@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [oRastor/fut20-web-app] FUT20 Integration (#1)


I agree! Basic autobuyer would be nice to leverage now before the actual game starts. Thanks a lot for updating.

**Comment by Forzabesiktas40** [comment]
Thanks to Orest and Vatsa for the support of making a new updated version off autobuyer, i ussed the the autobuyer from Orest and that wass the best one because it,s simple and fast, the only option to put it in the new autobyer is gold Squad fitness bidder.

**Comment by VatsaPatel** [comment]
I am very sorry guys, it slipped off my mind last night to put PR.
I am on a trip and won't be back until next Monday.

Again, very sorry.

**Comment by BzRk88** [comment]
Thats very sorry to hear for us. Is there no other possibility that someone can post the file? Have a good trip!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: VatsaPatel <notifications@github.com>
Verzonden: Tuesday, September 24, 2019 7:39:20 AM
Aan: oRastor/fut20-web-app <fut20-web-app@noreply.github.com>
CC: BzRk88 <hendriks_jimmy@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [oRastor/fut20-web-app] FUT20 Integration (#1)


I am very sorry guys, it slipped off my mind last night to put PR.
I am on a trip and won't be back until next Monday.

Again, very sorry.

**Comment by oRastor** [comment]
Search has been already fixed! Please, test buy and sell functionality!

**Comment by oRastor** [comment]
Tested. It's work!

**Comment by BzRk88** [comment]
so i can now just download the patch? from github
________________________________
Van: Orest Budzhak <notifications@github.com>
Verzonden: dinsdag 24 september 2019 10:32
Aan: oRastor/fut20-web-app <fut20-web-app@noreply.github.com>
CC: BzRk88 <hendriks_jimmy@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [oRastor/fut20-web-app] FUT20 Integration (#1)


Closed #1<https://github.com/oRastor/fut20-web-app/issues/1>.

**Comment by BzRk88** [comment]
You are the man orest! So many thanx. Now Lets see if iT picks something up. Did you try picking something up?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: MrBzRk™ .. <hendriks_jimmy@hotmail.com>
Verzonden: Tuesday, September 24, 2019 12:33:35 PM
Aan: oRastor/fut20-web-app <reply@reply.github.com>
Onderwerp: Re: [oRastor/fut20-web-app] FUT20 Integration (#1)

so i can now just download the patch? from github
________________________________
Van: Orest Budzhak <notifications@github.com>
Verzonden: dinsdag 24 september 2019 10:32
Aan: oRastor/fut20-web-app <fut20-web-app@noreply.github.com>
CC: BzRk88 <hendriks_jimmy@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [oRastor/fut20-web-app] FUT20 Integration (#1)


Closed #1<https://github.com/oRastor/fut20-web-app/issues/1>.

**Comment by oRastor** [comment]
Other man tries. I don't have FIFA 20.

вт, 24 сент. 2019 г. в 13:41, BzRk88 <notifications@github.com>:

**Comment by LaKo13** [comment]
This works - awesome. Thanks a lot for all your efforts.

**Comment by BzRk88** [comment]
Hey guys,

Do you all have problems with the buyer. And that its not seeing everything and has a lot of buys failed? I dont understand. I am seeing lots of hits on the console itself but the buyer doesnt any of them. Dont know if this is a bug or something else.  would love to here from you guys. Maybe i am using it wrong.
________________________________
Van: VatsaPatel <notifications@github.com>
Verzonden: maandag 23 september 2019 10:02
Aan: oRastor/fut20-web-app <fut20-web-app@noreply.github.com>
CC: BzRk88 <hendriks_jimmy@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [oRastor/fut20-web-app] FUT20 Integration (#1)


He guys, I am thinking of adding features:

  *   multiple player buy list, that will repeatedly analyze the market to find a snipe and instantly sell it for profit at that moment.
  *   Bidding watcher: auto bid players in last 30 sec at cheap from the wishlist, whilst watching current market price.
  *   Multiple filter support: run script on multiple filters and rotate through them instead of sticking to 1 card for 2 hours.
  *   Squad Overview: assess if unused card's price has skyrocketed due to SBC.

So what are your views? Any additions you would like?. Also, at the moment I am running into limitations of tampermonkey being sandboxed, So would you be fine with an electron app? Also market scraping would need to be done by a server, so don't know how to distribute access to everybody.

**Comment by oRastor** [comment]
This problem described in #2 issue.
I will work with this problem after EA open transfers for my account...

**Comment by BzRk88** [comment]
Hey orest,

Do hou have any idea how it is possible that the autobuyer doesnt see so many cards? And has so many fails? Sometimes i have the idea that it is not working like it should be. Or maybe it is just me. Do you have any idea? Love to hear from you.

Greetings jimmy

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Orest Budzhak <notifications@github.com>
Verzonden: Monday, September 30, 2019 8:37:07 AM
Aan: oRastor/fut20-web-app <fut20-web-app@noreply.github.com>
CC: BzRk88 <hendriks_jimmy@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [oRastor/fut20-web-app] FUT20 Integration (#1)


This problem described in #2<https://github.com/oRastor/fut20-web-app/issues/2> issue.
I will work with this problem after EA open transfers for my account...
